export const keywords = [
  "All",
  "React Js",
  "JavaScript",
  "Computer Applications",
  "Comedies",
  "Scene",
  "History",
  "Conversation",
  "Street Food",
  "Podcasts",
  "Recently Uploaded",
  "Watched",
  "New to you",
  "Never Watched",
  "Videos",
];
